# pylint: disable=missing-module-docstring
# Generated by Django 3.2.6 on 2021-09-10 11:50
"""
Auto generated code
"""
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    """
    Auto generated code
    """
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2021, 9, 10, 11, 50, 10, 973839, tzinfo=utc)),
        ),
    ]
