# pylint: disable=missing-module-docstring
# Generated by Django 3.2.6 on 2021-09-10 16:27
"""
Auto generated code
"""
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    """
     Auto generated code
    """
    dependencies = [
        ("blog", "0002_auto_20210910_1150"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
