# pylint: disable=missing-module-docstring
# Generated by Django 3.2.6 on 2021-09-13 12:50
"""
Auto generated code
"""
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    """
    Auto generated code
    """
    dependencies = [
        ("blog", "0004_auto_20210913_0931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestion",
            name="time",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2021, 9, 13, 12, 50, 27, 159357, tzinfo=utc)),
        ),
    ]
