# pylint: disable=missing-module-docstring
# Generated by Django 3.2.6 on 2021-09-14 13:30
"""
Auto generated code
"""
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):
    """
    Auto generated code
    """
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0007_auto_20210914_1318"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                default=None, related_name="likes", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="comment",
            name="time",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2021, 9, 14, 13, 30, 53, 275619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="time",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2021, 9, 14, 13, 30, 53, 275976, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name="Likes",
            fields=[
                ("id", models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("post", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="post_likes", to="blog.post")),
                ("user", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="user_likes", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
