# pylint: disable=missing-module-docstring
# Generated by Django 3.2.6 on 2021-09-14 16:45
"""
Auto generated code
"""
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    """
    Auto generated code
    """
    dependencies = [
        ("blog", "0008_auto_20210914_1330"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestion",
            name="time",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2021, 9, 14, 16, 45, 50, 811596, tzinfo=utc)),
        ),
    ]
