# pylint: disable=missing-module-docstring
# Generated by Django 3.2.6 on 2021-09-14 16:46
"""
Auto generated code
"""
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):
    """
    Auto generated code
    """
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0009_auto_20210914_1645"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="comment_post",
                to="blog.post"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="comment_user",
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="comment",
            name="time",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2021, 9, 14, 16, 46, 50, 134042, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="suggestion_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestion_user", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="suggetion_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestion_post", to="blog.post"),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="time",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2021, 9, 14, 16, 46, 50, 134425, tzinfo=utc)),
        ),
    ]
