# pylint: disable=missing-module-docstring
# Generated by Django 3.2.6 on 2021-09-15 13:01
"""
Auto generated code
"""
from django.db import migrations


class Migration(migrations.Migration):
    """
    Auto generated code
    """
    dependencies = [
        ("blog", "0011_auto_20210915_1232"),
    ]

    operations = [
        migrations.RenameField(
            model_name="suggestion",
            old_name="suggetion_post",
            new_name="suggestion_post",
        ),
    ]
