# pylint: disable=missing-module-docstring
# Generated by Django 3.2.6 on 2021-09-15 14:23
"""
Auto generated code
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Auto generated code
    """
    dependencies = [
        ("blog", "0012_rename_suggetion_post_suggestion_suggestion_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.AddField(
            model_name="likes",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
