# Generated by Django 3.2.6 on 2021-09-21 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Auto Generated code
    """

    dependencies = [
        ("blog", "0016_auto_20210921_1035"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name="reply", to="blog.comment"),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="reply",
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name="suggestion_reply", to="blog.suggestion"),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="status",
            field=models.CharField(default="suggested", max_length=20, null=True),
        ),
    ]
