# Generated by Django 3.2.6 on 2021-09-21 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Auto generated code
    """
    dependencies = [
        ("blog", "0017_auto_20210921_1045"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="file",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name="reply", to="blog.comment"),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="reply",
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name="suggestion_reply", to="blog.suggestion"),
        ),
    ]
